const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE';
const SEARCH_FOR_GIF = 'SEARCH_FOR_GIF';
const RECEIVE_GIF = 'RECEIVE_GIF';
const CHANGE_WEIRDNESS = 'CHANGE_WEIRDNESS';
const LIKE_GIF = 'LIKE_GIF';
const UNLIKE_GIF = 'UNLIKE_GIF';
const CALCULATE_WEIRDNESS = 'CALCULATE_WEIRDNESS';
const START_OVER = 'START_OVER';

export default {
    UPDATE_SEARCH_VALUE,
    SEARCH_FOR_GIF,
    RECEIVE_GIF,
    CHANGE_WEIRDNESS,
    LIKE_GIF,
    UNLIKE_GIF,
    CALCULATE_WEIRDNESS,
    START_OVER
}