const SEARCH_FOR_GIF = 'SEARCH_FOR_GIF';
const RECEIVE_GIF = 'RECEIVE_GIF';
const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE';
const LIKE_GIF = 'LIKE_GIF';

export default {
    SEARCH_FOR_GIF,
    RECEIVE_GIF,
    UPDATE_SEARCH_VALUE,
    LIKE_GIF
}